batch_size: 8
vis_epochs: 2
val_epochs: 4
vis_every: 300
val_every: 600
vis_grad: True
save_grid: False

iters_per_phase:
    epi: 60
    parallel: 60
    kmeans: 120
    planar: 100
    deform: 180
    refine: 10

epochs_per_phase:
    epi: 1
    parallel: 1
    kmeans: 1
    planar: 1
    deform: 1
    refine: 1

w_epi: 0.5
neg_ratio: 0.15
w_kmeans: 0.05
w_sparse: 0.001
w_warp: 0.1
w_tform: 1
w_recon: 0.5
l_recon: 1
lap_ratio: 0.001
lap_levels: 3
w_contr: 0.0005
